processScheduledJobCron: 0/10 * * * * ?  # every 10 seconds

spireClientUserName: "${SPIRE_CLIENT_USERNAME}"
spireClientPassword: "${SPIRE_CLIENT_PASSWORD}"
spireClientUrl: "${SPIRE_CLIENT_URL}"

jwtSharedSecret: "${JWT_SHARED_SECRET}"

customerServiceUrl: "${CUSTOMER_SERVICE_URL}"

maxMinutesRetryAfterFail: 1
maxCallbackFailCount: 5

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: ${PORT}
  requestLog:
    appenders:
      - type: json-console-access

logging:
  level: INFO
  appenders:
    - type: json-console

database:
  driverClass: org.postgresql.Driver
  url: "${VCAP_JDBC_URL}"
  schema: "${DATABASE_SCHEMA}"
  properties:
    charSet: UTF-8
  maxWaitForConnection: 30s
  validationQuery: "SELECT 1"
  minSize: ${DB_POOL_MIN_SIZE}
  maxSize: ${DB_POOL_MAX_SIZE}
  initialSize: ${DB_POOL_MIN_SIZE}
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

adminLogin: "${ADMIN_LOGIN}"
adminPassword: "${ADMIN_PASSWORD}"

login: "${BASIC_AUTH_USER}"
password: "${BASIC_AUTH_PASSWORD}"

redis:
  host: "${REDIS_HOST}"
  password: "${REDIS_PASSWORD}"
  port: "${REDIS_PORT}"
  timeout: "${REDIS_TIMEOUT}"
  database: 0
  ssl: "${REDIS_SSL}"
  poolMinIdle: "${REDIS_POOL_MIN_IDLE}"
  poolMaxTotal: "${REDIS_POOL_MAX_TOTAL}"
  keyPrefix: "${REDIS_KEY_PREFIX}"
  key: "${REDIS_KEY}"
  ttl:
    getLicenceByRef: "${REDIS_TTL_GET_LICENCE_BY_REF}"
    getAllLicences: "${REDIS_TTL_GET_ALL_LICENCES}"
    getLicencesByType: "${REDIS_TTL_GET_LICENCES_BY_TYPE}"
    getRegistration: "${REDIS_TTL_GET_REGISTRATION}"
    getRegistrations: "${REDIS_TTL_GET_REGISTRATIONS}"
