processScheduledJobCron: 0/10 * * * * ?  # every 10 seconds

spireClientUserName: "ENTER_USERNAME_HERE"
spireClientPassword: "ENTER_PASSWORD_HERE"
spireClientUrl: "https://lite-service-mocking-dev.cloudapps.digital/spire/fox/ispire/"

jwtSharedSecret: "demo-secret-which-is-very-long-so-as-to-hit-the-byte-requirement"

customerServiceUrl: "https://lite-customer-service-dev.cloudapps.digital"

maxMinutesRetryAfterFail: 1
maxCallbackFailCount: 5

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

logging:
  level: INFO
  appenders:
    - type: console
      includeCallerData : true
      logFormat: "[%mdc{corrID}] %d [%p] %marker %logger %m%n"
  loggers:
    uk.gov.bis.lite.common.spire.client: TRACE

database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres?currentSchema=permissionsvc
  user: postgres
  password: password
  properties:
    charSet: UTF-8
  maxWaitForConnection: 30s
  validationQuery: "SELECT 1"
  initialSize: 1
  minSize: 1
  maxSize: 3
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

adminLogin: "ENTER_USERNAME_HERE"
adminPassword: "ENTER_PASSWORD_HERE"

serviceLogin: "ENTER_USERNAME_HERE"
servicePassword: "ENTER_PASSWORD_HERE"